CREATE DATABASE Ejemplo;
USE Ejemplo;
CREATE TABLE Usuario(
IdUsuario INT NOT NULL Primary key AUTO_INCREMENT,
Nombre VARCHAR(50) NOT NULL,
Correo VARCHAR(50) NOT NULL,
Alias VARCHAR(20) NOT NULL,
Passwd VARCHAR(20) NOT NULL)