-- MySQL Script generated by MySQL Workbench
-- Thu Mar 19 18:21:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema credito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema credito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `credito` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema debito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema debito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `debito` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema edocuenta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema edocuenta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edocuenta` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema inversion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inversion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inversion` DEFAULT CHARACTER SET utf8 ;
USE `credito` ;

-- -----------------------------------------------------
-- Table `credito`.`ctas_credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `credito`.`ctas_credito` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `saldo` DECIMAL(10,2) NOT NULL,
  `fk_cliente` INT(11) NOT NULL,
  `no_cuenta` VARCHAR(20) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `debito` ;

-- -----------------------------------------------------
-- Table `debito`.`ctas_debito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `debito`.`ctas_debito` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `saldo` DECIMAL(10,2) NOT NULL,
  `fk_cliente` INT(11) NOT NULL,
  `no_cuenta` VARCHAR(20) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `edocuenta` ;

-- -----------------------------------------------------
-- Table `edocuenta`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edocuenta`.`cuenta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `no_cuenta` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `inversion` ;

-- -----------------------------------------------------
-- Table `inversion`.`ctas_inversion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inversion`.`ctas_inversion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `saldo` DECIMAL(10,2) NOT NULL,
  `fk_cliente` INT(11) NOT NULL,
  `no_cuenta` VARCHAR(20) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
